- name: Update cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install Python tools
  ansible.builtin.apt:
    name:
      - python3-venv
      - python3-pip
      - python3-dev
      - pipx
    state: present
    update_cache: false
  become: true

- name: Install common packages
  ansible.builtin.apt:
    name:
      - zip
      - 7zip
      - unzip
      - jq
      - dnsutils
      - sshpass
      - gnupg
      - curl
      - ca-certificates
      - git
      - sudo
      - nano
      - vim
      - wget
      - file
      - build-essential
      - libffi-dev
      - openssh-client
    state: present
    update_cache: false
  become: true

- name: Pipx ensurepath
  ansible.builtin.command:
    cmd: pipx ensurepath
  changed_when: true

- name: Install Ansible-lint
  ansible.builtin.apt:
    name: ansible-lint
    update_cache: false
  become: true

- name: Install wslu pkg on WSL
  ansible.builtin.apt:
    name: wslu
    state: present
    update_cache: false
  become: true
  when: "'WSL' in ansible_kernel"
