---
snowsql_snowflake_bin_download_url: https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.3-linux_x86_64.bash
snowsql_snowflake_sig_download_url: https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.3-linux_x86_64.bash.sig
snowsql_snowflake_gpg_keys: 2A3149C82551A34A
snowflake_cli_url: https://sfc-repo.snowflakecomputing.com/snowflake-cli/linux_x86_64/3.6.0/snowflake-cli-3.6.0.x86_64.deb
